name: era5-forge
channels:
 - conda-forge
dependencies:
 - python=3.9*
 - s3fs
 - dask
 - pandas
 - distributed
 - fsspec
 - numcodecs
 - prefect=1.2.4
 - xarray
 - netcdf4
 - scipy
 - zarr
 - cdsapi
 - cfgrib
 - h5netcdf
