name: era5-forge
channels:
 - conda-forge
dependencies:
 - python=3.9*
 - s3fs=2022.5.0
 - dask=2022.05.2
 - pandas=1.4.2
 - distributed=2022.5.2
 - fsspec=2022.5.0
 - numcodecs=0.9.1
 - prefect=1.2.4
 - xarray=2022.3.0
 - netcdf4=1.5.8
 - scipy=1.8.1
 - zarr=2.11.3
 - cdsapi=0.5.1
 - cfgrib=0.9.10.1
 - h5netcdf=1.1.0

 
